version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "snapshot-duplicator"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3e8d1bsuuxs5"
s3_prefix = "snapshot-duplicator"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
